### ISSUE TITLE
Chart List Tracker

### ISSUE THREAD

**Issue by shreshthmohan** [plotthatstory/viz_co#34]
- [ ] 1. Mace
- [ ] 2. Horizontal Bubble
- [ ] 3. Motion Bubble
- [ ] 4. Domino (Base)
- [ ] 5. Domino (Ribbon)
- [ ] 6. Overlapping area
- [ ] 7. Calendar
- [ ] 8. Ridgeline
- [ ] 9. Sankey
- [ ] 10. Line with band
- [ ] 11. Line with scatter
- [ ] 12. Triangle
- [ ] 13. Comparative bars
- [ ] 14. US Choropleth (Counties, States)
- [ ] 15. Chord
- [ ] 16. Parallel Connections
- [ ] 17. Stacker bar
- [ ] 18. Overlapping bars
- [ ] 19. Before-after bullet
